//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Picker.Postgresql
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public string id { get; set; }
        public string uid { get; set; }
        public string Content { get; set; }
        public Nullable<System.DateTimeOffset> CreatedAt { get; set; }
        public Nullable<System.DateTimeOffset> UpdatedAt { get; set; }
        public Nullable<System.DateTimeOffset> ProcessedAt { get; set; }
        public string type { get; set; }
    }
}
